### ISSUE TITLE
Create Project Input 應該清除狀態，並清除自動填入

### ISSUE THREAD

**Issue by allen880612** [allen880612/GitRepositoryAnalysisSystem#9]

**Comment by 110598071** [comment]
若verify GitRepoUrl或SonarUrl 未通過時，會自動清空兩者共計4欄的input (不會清空ProjectName and ProjectDescription Input)

**Comment by 110598071** [comment]
已針對所有Input新增autocompleted = off，但根據網路資料查詢後，chrome似乎有時會忽略自動填入的設定
